#!/usr/bin/env python3
"""Scan Dynamixel FTDI buses, bind left/right, write .skye + yaml.

Usage (Docker 内推荐):
  python3 /scripts/bind_leader_arms.py
  source /marvin_ws/.skye/leader_arms.env

  python3 /scripts/bind_leader_arms.py --dry-run
"""
from __future__ import annotations

import argparse
import os
import re
import sys
import time
from pathlib import Path

BAUD = 4_000_000
BY_ID = Path("/dev/serial/by-id")


def repo_paths() -> tuple[Path, Path]:
    here = Path(__file__).resolve().parent
    # Skye_ROS_Bridge: scripts/ 与 marvin_ws/ 同级
    if (here.parent / "marvin_ws").is_dir():
        root, marvin = here.parent, here.parent / "marvin_ws"
    elif Path("/marvin_ws").is_dir():
        root = Path("/scripts") if Path("/scripts").is_dir() else here
        marvin = Path("/marvin_ws")
    else:
        sys.exit("找不到 marvin_ws，请在仓库或 Docker(/marvin_ws) 中运行")
    return root, marvin


def list_ftdi() -> list[str]:
    if not BY_ID.is_dir():
        return []
    return sorted(p.name for p in BY_ID.iterdir() if "FTDI" in p.name)


def probe(name: str) -> bool:
    from dynamixel_sdk import PacketHandler, PortHandler

    port = str(BY_ID / name)
    pk = PortHandler(port)
    try:
        if not pk.openPort() or not pk.setBaudRate(BAUD):
            return False
        ph = PacketHandler(2.0)
        for i in range(1, 9):
            _, res, _ = ph.ping(pk, i)
            if res == 0:
                return True
        return False
    except Exception:
        return False
    finally:
        try:
            pk.closePort()
        except Exception:
            pass


def scan() -> list[str]:
    names = list_ftdi()
    print(f"发现 FTDI {len(names)} 个: {names or '(无)'}")
    ok = []
    for n in names:
        good = probe(n)
        print(f"  {'OK' if good else '--'}  {n}")
        if good:
            ok.append(n)
    return ok


def pick_two(cands: list[str]) -> tuple[str, str]:
    if len(cands) < 2:
        sys.exit(f"需要至少 2 路 Dynamixel 总线，当前 {len(cands)}")
    if len(cands) > 2:
        print("\n多套并存，请选择:")
        for i, n in enumerate(cands):
            print(f"  [{i}] {n}")
        li = int(input("左臂 index: ").strip())
        ri = int(input("右臂 index: ").strip())
        if li == ri or not (0 <= li < len(cands) and 0 <= ri < len(cands)):
            sys.exit("左右 index 非法")
        return cands[li], cands[ri]

    print("\n请拔掉【左臂】USB，拔完后回车…")
    input()
    for _ in range(20):
        now = set(list_ftdi())
        gone = [n for n in cands if n not in now]
        if len(gone) == 1:
            left = gone[0]
            right = cands[0] if cands[1] == left else cands[1]
            print(f"左={left}\n右={right}")
            print("请插回左臂 USB，插完后回车…")
            input()
            return left, right
        time.sleep(0.25)
    sys.exit("未检测到拔出变化，请重试")


def write_env(path: Path, left: str, right: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        "# auto-generated by bind_leader_arms.py\n"
        f'export ROBOT_LEADER_DYNAMIXEL_PORT_LEFT="{left}"\n'
        f'export ROBOT_LEADER_DYNAMIXEL_PORT_RIGHT="{right}"\n'
    )


def write_yaml_map(path: Path, left: str, right: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(f"left_by_id: {left}\nright_by_id: {right}\n")


def patch_dynamixel_port(path: Path, name: str) -> bool:
    if not path.is_file():
        return False
    text = path.read_text()
    new, n = re.subn(
        r'(dynamixel_port:\s*")[^"]*(")',
        rf"\g<1>{name}\2",
        text,
        count=1,
    )
    if n:
        path.write_text(new)
    return n > 0


def set_latency(names: list[str]) -> None:
    """拔插 USB 后 latency 会恢复默认，必须重新写成 1。"""
    for name in names:
        link = BY_ID / name
        if not link.exists():
            print(f"  skip latency: {name} 不存在")
            continue
        tty = os.path.basename(os.path.realpath(link))
        path = f"/sys/bus/usb-serial/devices/{tty}/latency_timer"
        try:
            with open(path, "w", encoding="ascii") as f:
                f.write("1\n")
            with open(path, encoding="ascii") as f:
                val = f.read().strip()
            print(f"  latency {tty}={val}")
        except OSError as e:
            print(f"  latency 失败 {tty}: {e}（可手动: echo 1 | sudo tee {path}）")


def apply(marvin: Path, left: str, right: str, dry: bool) -> None:
    env = marvin / ".skye" / "leader_arms.env"
    yml = marvin / ".skye" / "leader_arms.yaml"
    left_cfg = marvin / "install/share/factr_teleop/configs/grav_comp_m6_left.yaml"
    right_cfg = marvin / "install/share/factr_teleop/configs/grav_comp_m6_right.yaml"

    print("\n将写入:")
    print(f"  {env}")
    print(f"  {yml}")
    print(f"  {left_cfg.name} / {right_cfg.name}")
    if dry:
        print("[dry-run] 未写盘")
        return

    write_env(env, left, right)
    write_yaml_map(yml, left, right)
    patch_dynamixel_port(left_cfg, left)
    patch_dynamixel_port(right_cfg, right)
    print("设置 latency_timer=1 …")
    set_latency([left, right])
    print("已写入。当前 shell 请执行:")
    print(f"  source {env}")


def main() -> None:
    ap = argparse.ArgumentParser(description="绑定左右主臂 FTDI 串口")
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()
    _, marvin = repo_paths()
    cands = scan()
    left, right = pick_two(cands)
    apply(marvin, left, right, args.dry_run)


if __name__ == "__main__":
    main()
