<?xml version="1.0"?>
<package format="3">
  <name>skye_robot_driver</name>
  <version>0.1.0</version>
  <description>Skye / Gento dual-arm ROS2 driver (C++ L1 SDK)</description>
  <maintainer email="dev@tianji.local">tianji</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>rclcpp</depend>
  <depend>sensor_msgs</depend>
  <depend>std_srvs</depend>
  <exec_depend>launch_ros</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
